# WARNING: This is a TEMPLATE file only. 
# DO NOT commit actual passwords to Git!
#
# To create the actual secret, use one of these methods:
#
# Method 1 - kubectl command (recommended):
# kubectl create secret generic ema-db-secret \
#   --from-literal=username=YOUR_DB_USERNAME \
#   --from-literal=password=YOUR_DB_PASSWORD \
#   -n ema
#
# Method 2 - Use a secrets management tool like: 
# - Sealed Secrets
# - External Secrets Operator
# - HashiCorp Vault
# - AWS Secrets Manager
# - Azure Key Vault

apiVersion: v1
kind:  Secret
metadata:
  name:  ema-db-secret
  namespace: ema
type:  Opaque
stringData:
  username: REPLACE_WITH_DB_USERNAME
  password: REPLACE_WITH_DB_PASSWORD
